apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: default
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: us-central1-docker.pkg.dev/project-41-390015/capstone-products/products:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080