apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: default
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: us-central1-docker.pkg.dev/project-41-390015/capstone-orders/orders:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
