trigger:
- master

pool:
    vmImage: 'ubuntu-latest'
    
variables:
- group: 'GOOGLE_CREDENTIALS_GROUP'

steps:
- script: |
    echo "$(GOOGLE_CREDENTIALS)" | sed 's/\\n/\n/g' > creds.json
    export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/creds.json
    terraform init
  displayName: 'Terraform Init'
    
- script: |
    export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/creds.json
    terraform plan -out=tfplan -input=false
  displayName: 'Terraform Plan'
    
- script: |
    export GOOGLE_APPLICATION_CREDENTIALS=$(System.DefaultWorkingDirectory)/creds.json
    terraform apply -auto-approve -input=false tfplan
  displayName: 'Terraform Apply'